import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
});

export const metadata = {
  title: "Arif Basha K.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-200">
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-6rem)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
