import { Poppins } from "next/font/google";
import "./globals.css";
import TransistionProvider from "@/components/TransistionProvider";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
});

export const metadata = {
  title: "Arif Basha K.",
  description: "Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>
       <TransistionProvider>
        {children}
       </TransistionProvider>
      </body>
    </html>
  );
}
